// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { useShellStore } from '@/stores/shellStore';
import { safeStorage } from '@/lib/safeStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const authStorage = {
  getItem: (key: string) => safeStorage.getItem(key),
  setItem: (key: string, value: string) => safeStorage.setItem(key, value),
  removeItem: (key: string) => safeStorage.removeItem(key),
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: new Proxy({} as Record<string, string>, {
      get(_, prop: string) {
        if (prop === 'x-user-email') {
          return useShellStore.getState().userEmail || 'guest';
        }
        return undefined;
      },
      ownKeys() {
        return ['x-user-email'];
      },
      getOwnPropertyDescriptor(_, prop: string) {
        if (prop === 'x-user-email') {
          return { configurable: true, enumerable: true, value: useShellStore.getState().userEmail || 'guest' };
        }
        return undefined;
      },
    }),
  },
});